#!/usr/bin/env bash
set -e

COMPOSE_HOOK_ARGS="--config submodule/compose-hook.yml"

TEMP_SUBMODULE_DIR=$(mktemp -dt compose-testXXXXX)
(
cd "$TEMP_SUBMODULE_DIR"
git init -q .
git config user.name "test"
git config user.email "test@test.com"
cat << EOF > compose-hook.yml
master:
  project: a
EOF
git add compose-hook.yml
git commit -qma
)

git submodule --quiet add "$TEMP_SUBMODULE_DIR" submodule
git commit -qma
git push --all -q origin 2>&1
exit

EXPECTED
remote: compose-hook: master COMPOSE_PROJECT_NAME=a
remote: compose-hook: docker-compose pull
remote: pull
remote: compose-hook: docker-compose build
remote: build
remote: compose-hook: docker-compose up -d
remote: up -d
