#!/usr/bin/env bash
set -e

GIT_HOOK_INVOKE_HOW=pre-receive-args

cat << EOF > compose-hook.yml
master:
  project: a
test:
  project: b
EOF
git add compose-hook.yml
git commit -qma
git checkout -qb test
git push --all -q origin 2>&1
exit

EXPECTED
remote: compose-hook: master COMPOSE_PROJECT_NAME=a
remote: compose-hook: docker-compose pull
remote: pull
remote: compose-hook: docker-compose build
remote: build
remote: compose-hook: docker-compose up -d
remote: up -d
remote: compose-hook: test COMPOSE_PROJECT_NAME=b
remote: compose-hook: docker-compose pull
remote: pull
remote: compose-hook: docker-compose build
remote: build
remote: compose-hook: docker-compose up -d
remote: up -d
