#!/usr/bin/env bash
set -e

MOCK_COMPOSE_FAIL_COMMAND=build

cat << EOF > compose-hook.yml
master:
  project: a
EOF
git add compose-hook.yml
git commit -qma
git push --all -q origin 2>&1
exit

EXPECTED
remote: compose-hook: master COMPOSE_PROJECT_NAME=a
remote: compose-hook: docker-compose pull
remote: pull
remote: compose-hook: docker-compose build
remote: compose-hook: exit status 1
 ! [remote rejected] master -> master (pre-receive hook declined)
