#!/usr/bin/env bash
set -e

cat << EOF > compose-hook.yml
master:
EOF
git add compose-hook.yml
git commit -qma
git push --all -q origin 2>&1 || true
exit

EXPECTED
remote: compose-hook: master: no project name
 ! [remote rejected] master -> master (pre-receive hook declined)
