#!/usr/bin/env bash
set -e

COMPOSE_HOOK_ARGS="--config test.yml"

cat << EOF > test.yml
master:
  project: a
EOF
git add test.yml
git commit -qma
git push --all -q origin 2>&1
exit

EXPECTED
remote: compose-hook: master COMPOSE_PROJECT_NAME=a
remote: compose-hook: docker-compose pull
remote: pull
remote: compose-hook: docker-compose build
remote: build
remote: compose-hook: docker-compose up -d
remote: up -d
